
# .readthedocs.yaml
# A corrected and robust configuration for Read the Docs

version: 2

# Set the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Define the Sphinx configuration path
sphinx:
  configuration: docs/source/conf.py

# Define Python package installation steps
python:
  install:
    # First, install dependencies from your requirements file
    - requirements: docs/requirements.txt
    
    # Then, install the project itself.
    # A regular install is sufficient for the build process.
    - method: pip
      path: .