from linear_inference.vector_space.linear_form import LinearForm
from linear_inference.vector_space.vector_space import VectorSpace, HilbertSpace
from linear_inference.vector_space.linear_operator import LinearOperator
from linear_inference.vector_space.euclidean_space import EuclideanSpace
