"""Numerical methods built on the algebraic core."""

from .functional_calculus import (
    OperatorFunction,
    apply_operator_function,
    iter_lanczos_tridiagonalise,
    lanczos_tridiagonalise,
    operator_exp,
    operator_function,
    operator_inverse_sqrt,
    operator_log,
    operator_power,
    operator_quadratic_form,
    operator_sqrt,
)

from .randomised import (
    Estimate,
    LowRankCholesky,
    LowRankEig,
    LowRankSVD,
    random_cholesky,
    random_diagonal,
    random_eig,
    random_range,
    random_svd,
    random_trace,
)
from .preconditioners import IdentityPreconditioner, JacobiPreconditioner
from .solvers import (
    BiCGStabSolver,
    CGSolver,
    CholeskySolver,
    ConvergenceError,
    DirectSolver,
    EigenSolver,
    InverseOperator,
    IterativeSolver,
    LeastSquaresSolver,
    LinearSolver,
    LSQRSolver,
    LUSolver,
    MinResSolver,
    SolveResult,
)

__all__ = [
    "BiCGStabSolver",
    "Estimate",
    "LowRankCholesky",
    "LowRankEig",
    "LowRankSVD",
    "random_cholesky",
    "random_diagonal",
    "random_eig",
    "random_range",
    "random_svd",
    "random_trace",
    "OperatorFunction",
    "apply_operator_function",
    "iter_lanczos_tridiagonalise",
    "lanczos_tridiagonalise",
    "operator_exp",
    "operator_function",
    "operator_inverse_sqrt",
    "operator_log",
    "operator_power",
    "operator_quadratic_form",
    "operator_sqrt",
    "CGSolver",
    "CholeskySolver",
    "ConvergenceError",
    "DirectSolver",
    "EigenSolver",
    "IdentityPreconditioner",
    "InverseOperator",
    "IterativeSolver",
    "JacobiPreconditioner",
    "LSQRSolver",
    "LUSolver",
    "LeastSquaresSolver",
    "LinearSolver",
    "MinResSolver",
    "SolveResult",
]
